CREATE TABLE IF NOT EXISTS SONGS(
  songId INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  artist VARCHAR(100) NOT NULL,
  youtubeId VARCHAR(100) NOT NULL,
  genre VARCHAR(50) NULL,
  PRIMARY KEY (songId)
);

CREATE TABLE IF NOT EXISTS PLAYLISTS(
  playlistId INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  PRIMARY KEY (playlistId)
);

CREATE TABLE IF NOT EXISTS PLAYLIST_SONGS(
  id INT NOT NULL,
  playlistId INT NOT NULL,
  songId INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (playlistId) REFERENCES PLAYLISTS (playlistId),
  FOREIGN KEY (songId) REFERENCES SONGS (songId),
);